image: node:10.15.3

variables:
  PUBLIC_URL: /desafio_agendaedu

stages:
  - test

before_script:
  # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
  - curl -o- -L https://yarnpkg.com/install.sh | bash

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn install # Install all dependencies
    - yarn test:final # Test for prod
  only:
    - master # Only run on master branch
