image: node:10.15.3

variables:
  PUBLIC_URL: /desafio_agendaedu

stages:
  - deploy

before_script:
  # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
  - curl -o- -L https://yarnpkg.com/install.sh | bash

cache:
  paths:
    - node_modules/
    - .yarn

test:
  stage: test
  script:
    - yarn install # Install all dependencies
    - yarn test # Test for prod
  artifacts:
    paths:
      - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
